Update aboutus.html
mlsacbvp/MLSAC-Website pull request #90
Opened 2022-08-05 16:50 UTC by AK-shat-JAIN

Fixed Typo in hollistic -> holistic

2022-08-06 19:00 UTC, void-ness commented
Hey, I the changes requested looks good to me. There's one more grammatical error on the same page in first question. can you correct that too. try searching in the "we are one of ... " line. If possible you can run a spell check on all the text of the about us page content and see it there are any other issues too?

2022-08-06 19:01 UTC, void-ness requested changes
Hey, I the changes requested looks good to me. There's one more grammatical error on the same page in first question. can you correct that too. try searching in the "we are one of ... " line. If possible you can run a spell check on all the text of the about us page content and see it there are any other issues too?

2022-08-06 22:04 UTC, AK-shat-JAIN commented
Hi, I have corrected that issue please review

2022-08-07 20:08 UTC, void-ness approved these changes

2022-08-07 20:09 UTC, merged